version: '3'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: workers

  # server:
  #   build:
  #     context: ./packages/server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   restart: always
