id = "openai_reasoning_worker_completions"
name = "OpenAI Reasoning Worker (Completions API)"
entrypoint_path = "openai_reasoning_worker_completions.ts"
config_schema_path = "config_schema.json"
type = "bun"
